### ISSUE TITLE
NextJS  13 TS/Zod  dependency issue

### ISSUE THREAD

**Issue by akdeb** [st3w4r/openai-partial-stream#11]
First off thank you for contributing towards building this. I think this is super useful in building streaming applications with function calling.

I am trying to use this in React with NextJS 13. I am also using the Vercel AI SDK's `useCompletion` hook on the client side that then calls an API route in the api directiory to stream the responses. I get this error with this setup: 

```
./node_modules/typescript/lib/typescript.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/typescript/lib/typescript.js
./node_modules/zod-to-ts/dist/index.js
./node_modules/openai-partial-stream/dist/chunk-66SDEIDM.mjs
./node_modules/openai-partial-stream/dist/index.mjs
./src/app/api/completion/route.ts
./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fcompletion%2Froute&page=%2Fapi%2Fcompletion%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fcompletion%2Froute.ts&appDir=%2FUsers%2Fakashdeepdeb%2FDesktop%2Ftopshelf%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2Fakashdeepdeb%2FDesktop%2Ftopshelf&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./src/app/api/completion/route.ts?__next_edge_ssr_entry__
<w> [webpack.cache.Pack
```

Any ideas if this is related to a zod to ts version issue?

**Comment by st3w4r** [comment]
Hi @akdeb, thank you for reporting the issue. I will investigate.

**Comment by st3w4r** [comment]
The zod-to-ts have replaced by zod-to-json-schema, on the latest version [0.3.7](https://www.npmjs.com/package/openai-partial-stream/v/0.3.7)
