### ISSUE TITLE
Example with postcodes not working

### ISSUE THREAD

**Issue by kancur** [st3w4r/openai-partial-stream#17]
Hey! Unfortunately I'm having a hard time getting this to run correctly. 
 
 I'm using copy-pasted postcodes example from [readme](https://github.com/st3w4r/openai-partial-stream?tab=readme-ov-file#usage-with-stream-and-entity-parsing-with-multiple-entities).

**Unfortunately, it only detects the last entity:**

![image](https://github.com/st3w4r/openai-partial-stream/assets/49352605/196a1d3c-6c8e-4332-8097-73c6d89d0f36)

![image](https://github.com/st3w4r/openai-partial-stream/assets/49352605/9e53f39b-70a1-402e-9a18-3da71c3fb5ec)

Expected output based on ReadMe:
```
{ index: 0, status: 'COMPLETED', data: { name: 'Los Angeles', postcode: '90001', population: 3971883 }, entity: 'postcodes' }
{ index: 1, status: 'COMPLETED', data: { name: 'San Francisco', postcode: '94102', population: 883305 }, entity: 'postcodes' }
{ index: 2, status: 'COMPLETED', data: { name: 'San Diego', postcode: '92101', population: 1425976 }, entity: 'postcodes'}
```

**If I iterate over the `entityStream` instead, it looks like this:**

![image](https://github.com/st3w4r/openai-partial-stream/assets/49352605/78a27032-26c4-48d0-a270-617d74a03cee)

![image](https://github.com/st3w4r/openai-partial-stream/assets/49352605/66f7b428-0866-415d-a5bc-590d020a67e2)

Is this some known issue, or did I miss anything? Thanks for your help!

**Comment by st3w4r** [comment]
Hello thank you for reporting, this is indeed not the expected behavior, let me investigate.

**Comment by st3w4r** [comment]
The alias for the model `gpt-3.5-turbo` has recently been updated. When pointing it to the old model, it works as expected.

> The gpt-3.5-turbo model alias will be automatically upgraded from gpt-3.5-turbo-0613 to gpt-3.5-turbo-0125 on February 16th.
https://platform.openai.com/docs/models/gpt-3-5-turbo

This may be due to a difference in how the tokens are returned in the stream, which could reveal a bug in the parser. I'm looking at the parser and trying to come up with a fix.

**Comment by kancur** [comment]
Awesome, thank you, will test later! :-)
