### ISSUE TITLE
Only OpenAI's API is supported?

### ISSUE THREAD

**Issue by yuguaa** [st3w4r/openai-partial-stream#25]

**Comment by yuguaa** [comment]
![image](https://github.com/user-attachments/assets/6a72942f-efef-42ae-afee-2183b1dfcdf7)
![image](https://github.com/user-attachments/assets/adf6f118-5877-4a59-99d0-f00bd4c54ba0)

**Comment by st3w4r** [comment]
Hi, could you share more details about your goal and which model provider, aside from OpenAI, you're looking to use?

**Comment by yuguaa** [comment]
> Hi, could you share more details about your goal and which model provider, aside from OpenAI, you're looking to use?

I'm using the Qwen Plus model. My goal is to convert fragmented JSON into the standard JSON format. I wonder if there is a Transformer that can be used to do this conversion. I just need to input the non-standard JSON strings.

**Comment by yuguaa** [comment]
Thank you so much for your efforts. However, I have switched to another library which has been of great help to me in solving my problem.The lib name is [wtf-json](https://github.com/yoannchb-pro/wtf-json)

**Comment by st3w4r** [comment]
> > Hi, could you share more details about your goal and which model provider, aside from OpenAI, you're looking to use?
> 
> 
> 
> I'm using the Qwen Plus model. My goal is to convert fragmented JSON into the standard JSON format. I wonder if there is a Transformer that can be used to do this conversion. I just need to input the non-standard JSON strings.

Indeed, the handler is designed to handle a specific data stream format provided by OpenAI. Before passing the data downstream, it will need to be updated. For now, this can be accomplished by understanding the internal structure of the handler and formatting it accordingly. The JSON closer is a generic component that can be reused. But, it will require some customization for your specific use case.

**Comment by st3w4r** [comment]
> Thank you so much for your efforts. However, I have switched to another library which has been of great help to me in solving my problem.The lib name is [wtf-json](https://github.com/yoannchb-pro/wtf-json)

Nice, thanks for sharing. Glad it solves your use case.
